pipeline {
    agent any

    environment {
        DOCKER_HUB_CRED = 'dockerhub-cred' 
        IMAGE_NAME = 'angelkwatra/flask-cicd-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning from GitHub...'
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image...'
                script {
                    dockImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}", "LAB/EXPERIMENT7/flask-app")
                }
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                echo 'Authenticating and Pushing Image to Docker Hub...'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CRED) {
                        dockImage.push()
                        dockImage.push('latest')
                    }
                }
            }
        }
    }
}
